# Generated by Django 5.1.6 on 2025-02-11 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.IntegerField(verbose_name='Номер стола')),
                ('items', models.JSONField(verbose_name='Список блюд с ценами')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('в ожидании', 'В ожидании'), ('готово', 'Готово'), ('оплачено', 'Оплачено')], default='в ожидании', max_length=20, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
        ),
    ]
